spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/master-authorizer
    username: postgres
  application:
    name: master-authorizer
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        client:
          articles-client:
            registration:
              client-id: articles-client
              client-secret: "{noop}secret"
              client-name: Articles Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/articles-client-oidc
              scopes:
                - openid
          authorities-reader:
            registration:
              client-id: authorities-reader
              client-secret: "{noop}authorities-reader"
              client-name: authorities-reader
              client-authentication-methods: 
                - client_secret_post
                - client_secret_basic
              authorization-grant-types: client_credentials
              scopes: authorities.read
              redirect-uris: http://127.0.0.1:8090/login/oauth2/code/authorities-reader
server:
  port: 9000
  
